spring:
  datasource:
    url: jdbc:postgresql://10.10.100.100:5432/postgres
    username: parcoursup
    password: Parcoursup123!
  batch:
    initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc.lob.non_contextual_creation: true